version: '3.8'
services:
  # 27017
  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network
    restart: unless-stopped

  # 5000
  backend:
    build: ./backend/.
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tasks
      - PORT=5000
      - REDIS_URI=redis://redis:6379
    networks:
      - mongo-network
      - backend-network
    restart: unless-stopped

  # 3000
  frontend:
    build: ./frontend/.
    container_name: frontend
    environment:
      - BACKEND_API=http://localhost:3000/tasks
    networks:
      - backend-network
      - frontend-network
    restart: unless-stopped


  proxy:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - backend-network
      - frontend-network

  # 6379
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - backend-network

networks:
  mongo-network:
    driver: bridge
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
